---
author: "Alec L. Robitaille"
output: github_document
editor_options: 
  chunk_output_type: console
---

# Homework: Week 8
2021-09-08 [updated: `r Sys.Date()`]

```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rethinking)
options(digits = 2, scipen = 999)
```

### Setup

```{r}
# Packages
library(ggdag)
library(dagitty)
library(data.table)
library(ggplot2)
library(rethinking)
library(cmdstanr)
library(posterior)
library(bayesplot)
library(boot)

# Functions
dag_plot <- function(dag) {
	stat <- node_status(dag, FALSE)
	stat$data$status[is.na(stat$data$status)] <- 'intermediate'
	ggplot(stat, aes(x = x, y = y, xend = xend, yend = yend)) +
	  geom_dag_point(aes(color = status), alpha = 0.5, size = 15) +
	  geom_dag_edges() +
		labs(color = '') + 
	  geom_dag_text(color = 'black') +
		scale_color_manual(values = list('exposure' = '#35608DFF',
																		 'outcome' = '#22A884FF',
																		 'intermediate' = 'grey50')) + 
	  theme_void()
}

cmd_draws <- function(model) {
	as_draws_df(model$draws())
}
```


## Question 1


### Data
```{r}
data(reedfrogs)
DT <- data.table(reedfrogs)
precis(DT)
```


```{r}
register_knitr_engine(override = FALSE)
```

```{cmdstan, output.var = 'model_frogs_1', cache = TRUE}
```

```{r, cache = TRUE}
model_frogs_1_stan <- 'model_frogs_1.stan'
writeLines(readLines(model_frogs_1_stan))
model_frogs_1 <- cmdstan_model(model_frogs_1_stan, cpp_options = list(stan_threads = TRUE))

model_data <- c(
	as.list(DT[, .(
		survival = surv,
		density,
		predation = as.integer(pred),
		size = as.integer(size),
		tank = seq.int(.N)
	)]), 
	N = DT[, .N]
)

model_frogs_1_sample <-
	model_frogs_1$sample(
		data = model_data,
		chains = 4,
		parallel_chains = 4,
		threads_per_chain = 4
	)

model_frogs_1_draws <- cmd_draws(model_frogs_1_sample)

mcmc_areas(model_frogs_1_draws, regex_pars = 'alpha')
mcmc_areas(model_frogs_1_draws, regex_pars = 'p\\[')
```


```{cmdstan, output.var = 'model_frogs_2', cache = TRUE}
```

```{r, cache = TRUE}
model_frogs_2_stan <- 'model_frogs_2.stan'
writeLines(readLines(model_frogs_2_stan))
model_frogs_2 <- cmdstan_model(model_frogs_2_stan, cpp_options = list(stan_threads = TRUE))
model_frogs_2_sample <-
	model_frogs_2$sample(
		data = model_data,
		chains = 4,
		parallel_chains = 4,
		threads_per_chain = 4
	)
model_frogs_2_draws <- cmd_draws(model_frogs_2_sample)
mcmc_areas(model_frogs_2_draws, regex_pars = 'predation')
```

```{cmdstan, output.var = 'model_frogs_3', cache = TRUE}
```

```{r, cache = TRUE}
model_frogs_3_stan <- 'model_frogs_3.stan'
writeLines(readLines(model_frogs_3_stan))
model_frogs_3 <- cmdstan_model(model_frogs_3_stan, cpp_options = list(stan_threads = TRUE))
model_frogs_3_sample <-
	model_frogs_3$sample(
		data = model_data,
		chains = 4,
		parallel_chains = 4,
		threads_per_chain = 4
	)
model_frogs_3_draws <- cmd_draws(model_frogs_3_sample)
mcmc_areas(model_frogs_3_draws, regex_pars = 'size')
```

```{cmdstan, output.var = 'model_frogs_4', cache = TRUE}
```

```{r, cache = TRUE}
model_frogs_4_stan <- 'model_frogs_4.stan'
writeLines(readLines(model_frogs_4_stan))
model_frogs_4 <- cmdstan_model(model_frogs_4_stan, cpp_options = list(stan_threads = TRUE))
model_frogs_4_sample <-
	model_frogs_4$sample(
		data = model_data,
		chains = 4,
		parallel_chains = 4,
		threads_per_chain = 4
	)
model_frogs_4_draws <- cmd_draws(model_frogs_4_sample)
mcmc_areas(model_frogs_4_draws, regex_pars = 'beta')
```

